---
default_language_version:
  python: python3.9

ci:
  autofix_commit_msg: |
    "refactor[pre-commit.ci]: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci"
  autofix_prs: true
  autoupdate_commit_msg: "bump[pre-commit.ci]: auto-update pre-commit hooks"
  autoupdate_schedule: weekly
  skip: [pylint, mypy, eslint]
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: [ "--django" ]
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [ --format, parsable, --strict ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ['-iii', '-ll', '-s', 'B404', 'B602', 'B603', 'B607']
        language_version: python3.9
        exclude: ^test/

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [ --in-place, --wrap-summaries=115, --wrap-descriptions=120 ]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-typing-imports",
          "flake8-bugbear",
          "flake8-comprehensions",
          "flake8-mutable",
          "flake8-print",
          "flake8-simplify",
          "flake8-django"
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [ cython ]
      - id: isort
        name: isort (pyi)
        types: [ pyi ]

  - repo: https://github.com/rtts/djhtml
    rev: v1.4.9
    hooks:
      - id: djhtml

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: ["toml"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.1
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest
        exclude: |
            (?x)^(
                .*\/vendor.*|
                .*one_barangay\/static\/assets\/.*\.js
            )$

  - repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        args: [ "--load-plugins=pylint_django", "--django-settings-module=one_barangay.settings" ]
        additional_dependencies:
          - pylint_django
          - django
          - sentry-sdk
          - python-dotenv
          - google-cloud-secret-manager
          - google-api-python-client
          - firebase_admin
          - faker
          - azure-storage-blob
          - azure-core
          - django-storages

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies: [
          djangorestframework-stubs,
          django-stubs,
          django,
          types-requests,
          sentry-sdk,
          python-dotenv,
          google-cloud-secret-manager,
          firebase_admin,
          faker,
          azure-storage-blob,
          azure-core,
          django-storages,
          types-python-dateutil
        ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]
